const INSTALLMENT_PENDING = 'PENDING';
const LIST_CREATED = 'LIST_CREATED';
const INSTALLMENT_LOGGED = 'LOGGED';
const LIST_LIMIT = 20000;
const REFERENCE_NO_CREATED = 'REFERENCE_NO_CREATED';

module.exports = {
  INSTALLMENT_PENDING,
  INSTALLMENT_LOGGED,
  LIST_CREATED,
  LIST_LIMIT,
  REFERENCE_NO_CREATED,
};
