const INSTALLMENT_PENDING = 'PENDING';
const LIST_CREATED = 'LIST_CREATED';
const INSTALLMENT_LOGGED = 'LOGGED';
const REFERENCE_NO_CREATED = 'REFERENCE_NO_CREATED';

const PAYMENT_MODES = {
  CASH: 'CASH',
  DOP_CHEQUE: 'DOP_CHEQUE',
  NON_DOP_CHEQUE: 'NON_DOP_CHEQUE',
};

const LIST_LIMITS = {
  [PAYMENT_MODES.CASH]: 20000,
  [PAYMENT_MODES.DOP_CHEQUE]: 100000,
};

const PORTAL_PAY_MODE_MAP = {
  [PAYMENT_MODES.CASH]: 'C',
  [PAYMENT_MODES.DOP_CHEQUE]: 'DC',
  [PAYMENT_MODES.NON_DOP_CHEQUE]: 'NDC',
};

module.exports = {
  INSTALLMENT_PENDING,
  INSTALLMENT_LOGGED,
  LIST_CREATED,
  LIST_LIMITS,
  REFERENCE_NO_CREATED,
  PAYMENT_MODES,
  PORTAL_PAY_MODE_MAP,
};
